#spring.application.name=api

# Configuração de Conexaão com o PostgreSQL.
spring.datasource.url=jdbc:postgresql://localhost:5432/beleza_studio_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver


# Configuração do hibernate / JPA.
#
# Dialeto específico para otimizar as consultas no Postgres
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Exibe os comandos SQL no console do Intellij (ótimo para debugar no TCC).
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#REGRA DE OURO AQUI
# Como nós já criamos as tabelas manualmente com o script SQL perfeito,
# usamos 'validate' para o Spring apenas checar se as entidades Java batem com o banco.
# NUNCA use 'update' ou 'create' aqui agora, senão o Hibernate vai bagunçar nossas Views e Functions.
spring.jpa.hibernate.ddl-auto=validate

#CONFIGURAÇÃO DE SEGURANÇA:
api.security.token.secret="senha-secreta-padrao-123"